import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def generate_smart_draft(raw_text: str) -> str:
    """
    Feature 2: Vernacular AI Smart Draft Engine.
    Converts raw Hinglish/English input into a formal botanical patent claim.
    """
    system_prompt = """
    You are an expert Ayurvedic intellectual property (IP) lawyer and botanist working for the Ministry of Ayush, Government of India.
    Your job is to take raw, vernacular, or conversational input from citizens (often in Hinglish or simple English) describing a traditional remedy.
    You must format this into a highly structured, legally defensible botanical patent claim.
    Structure your response strictly as follows (use ALL CAPS for headers, do NOT use markdown asterisks like **):
    TITLE: [A formal, scientific title]
    ABSTRACT: [A brief 2-sentence summary]
    BOTANICAL INGREDIENTS: [List ingredients with scientific names if possible]
    METHOD OF PREPARATION: [Formalized steps]
    TRADITIONAL CLAIM: [The specific medicinal use case]
    
    CRITICAL RULES:
    1. Do NOT include any introductory or conversational text. Output ONLY the formatted claim.
    2. Do NOT use markdown bolding (asterisks).
    3. If the user input is completely nonsensical, dangerous, toxic (like petrol/chemicals), or lacks any botanical/Ayurvedic basis, DO NOT use the structure above. Instead, directly reply with: "REJECTED: This input lacks traditional botanical precedence or contains toxic/non-Ayurvedic elements and cannot be patented under Indian Traditional Knowledge laws."
    """
    try:
        chat_completion = groq_client.chat.completions.create(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": raw_text}
            ],
            model="qwen/qwen3.6-27b",
            temperature=0.2, # Low temperature for strict, formal output
            max_tokens=4000,
        )
        raw_response = chat_completion.choices[0].message.content
        
        # Remove the <think>...</think> block generated by reasoning models like Qwen. 
        clean_response = raw_response
        if "<think>" in clean_response:
            if "</think>" in clean_response:
                clean_response = clean_response.split("</think>")[-1].strip()
            else:
                clean_response = "Drafting... Please try again or wait for full generation."
        return clean_response
    except Exception as e:
        return f"Error generating draft: {str(e)}"
def query_ip_sakti(query: str, retrieved_context: str = "") -> str:
    """
    Feature 1: IP-SAKTI Core (Strict-Citation RAG Assistant)
    Answers legal queries based strictly on provided IP law context.
    """
    system_prompt = """
    You are IP-SAKTI, the official legal AI assistant for the Ministry of Ayush.
    You answer questions regarding intellectual property rights, bio-piracy, and traditional knowledge protection in India and Internationally.
    
    CRITICAL RULE 1 (JURISDICTION): The user will specify [Jurisdiction: INDIA] or [Jurisdiction: INTERNATIONAL]. Keep your answer strictly relevant to the requested jurisdiction. Never conflate the two.
    
    CRITICAL RULE 2 (CLASSIFICATION FLOW): If the user asks to "Classify my Ayurvedic product" or similar, you MUST act as a classification wizard. Ask 2-3 minimum clarifying questions to determine if their product is a:
    1. Classical/Generic Medicine (drawn from First-Schedule authoritative text)
    2. Patent-or-Proprietary Medicine
    3. New Drug (requiring clinical proof)
    4. Phytopharmaceutical or Cosmetic
    Explain what each category requires regarding IP and Access-and-Benefit-Sharing (ABS) posture (e.g. Classical faces Sec 3(p) patenting bar).
    
    CRITICAL RULE 3 (CONTEXT & DISCLAIMER): Prioritize answering using the provided Context Block if it is relevant. 
    ALWAYS end your response with this EXACT disclaimer: "DISCLAIMER: This is an AI-generated informational response and not formal legal advice."
    
    FORMATTING RULE: Keep your responses highly structured, concise (3-4 paragraphs max), and professional. Use bullet points where appropriate.
    """
    
    user_prompt = f"""
    Context Block (Official IP Laws & Mandates):
    {retrieved_context if retrieved_context else "No specific legal context loaded for this query."}
    
    User Query: {query}
    """

    try:
        chat_completion = groq_client.chat.completions.create(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            model="qwen/qwen3.6-27b",
            temperature=0.1,
            max_tokens=4000,
        )
        raw_response = chat_completion.choices[0].message.content
        
        # Remove the <think>...</think> block generated by reasoning models like Qwen. 
        clean_response = raw_response
        if "<think>" in clean_response:
            if "</think>" in clean_response:
                clean_response = clean_response.split("</think>")[-1].strip()
            else:
                # If it got cut off before </think>, then the whole response is just thoughts.
                clean_response = "Processing..."
        return clean_response
    except Exception as e:
        return f"Error querying IP-SAKTI: {str(e)}"
