name: Keep Alive Render Backend

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend API
        run: |
          curl -i -s -S --max-time 30 https://root-claim.onrender.com/health
